Repository ProyectoUnidad8/frontend, pull requests merged in 2023-02, with the labels that each got.

#3 feat/8 adoption pet section
  src/App.tsx
  src/assets/css/style.css
  src/components/adoptPet/petAdopt.tsx
  src/components/navigation/Navbar.js
  src/containers/pages/PageAdoptPets.tsx
  src/functions/adoptFunction.ts
  src/index.tsx
  src/interfaces/IAdopt.ts
Labels: feature

#4 add modal and send application to adopt pet
  src/assets/css/style.css
  src/assets/img/sad-dog.png
  src/assets/img/smile-dog.png
  src/components/adoptPet/petAdopt.tsx
  src/components/modals/ModalApplicationAdopt.tsx
  src/containers/pages/PageAdoptPets.tsx
  src/functions/adoptFunction.ts
  src/interfaces/IAdopt.ts
  tsconfig.json
Labels: feature

#5 show only not adopted
  src/components/adoptPet/petAdopt.tsx
  src/containers/pages/PageAdoptPets.tsx
Labels: feature

#6 add function login and set token in localStorage
  package-lock.json
  package.json
  src/components/adoptPet/petAdopt.tsx
  src/components/modals/ModalApplicationAdopt.tsx
  src/containers/auth/Login.js
  src/containers/auth/Login.tsx
  src/functions/adoptFunction.ts
  src/functions/login.ts
  src/utils/token.ts
  src/utils/urls.ts
Labels: feature

#7 Feat/14 add crud adoption
  public/index.html
  src/assets/css/style.css
  src/assets/js/bootstrap.min.js
  src/assets/js/jquery.min.js
  src/assets/js/plugins.js
  src/components/applications/applications.tsx
  src/components/modals/ModalAdminPetAdopt.tsx
  src/components/modals/ModalAdminPetAdoptCrud.tsx
  src/components/modals/ModalApplicationAdopt.tsx
  src/containers/Home.tsx
  src/containers/admin/AdminAdoptionPage.tsx
  src/containers/admin/AdminApplications.tsx
  src/functions/Admin/AdminAdoptPet.ts
  src/functions/Admin/AdminApplications.ts
  src/interfaces/IAdopt.ts
  src/interfaces/IApplications.ts
Labels: feature

#8 remove files and format code
  README.md
  README.old.md
  public/index.html
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/assets/css/style.css
  src/components/modals/ModalApplicationAdopt.tsx
  src/components/navigation/Navbar.js
  src/components/pet/Mascota.tsx
  src/containers/Home.tsx
  src/containers/admin/MascotaAdmin.jsx
  src/containers/auth/Login.tsx
  src/containers/pages/PageAdoptPets.tsx
  src/functions/Admin/AdminAdoptPet.ts
  src/functions/Admin/AdminApplications.ts
  src/functions/AuthLogin.ts
  src/functions/Customers.ts
  src/functions/Diagnostic.ts
  src/functions/Pets.ts
  src/functions/adoptFunction.ts
  src/hocs/layout.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/reportWebVitals.ts
  src/utils/Auth.js
  src/utils/Auth.tsx
  src/utils/ClearLocalStorage.ts
  src/utils/LocalStorage.ts
  src/utils/export.jsx
  src/utils/loader.js
Labels: refactor

#9 edit bug in nav
  src/assets/css/style.css
  src/components/navigation/Navbar.js
  src/containers/auth/Login.tsx
Labels: refactor

#10 add create user
  src/assets/css/style.css
  src/components/applications/applications.tsx
  src/components/modals/ModalAdminUsers.tsx
  src/components/modals/ModalApplicationAdopt.tsx
  src/components/pet/Mascota.tsx
  src/containers/admin/AdminApplications.tsx
  src/containers/admin/ClienteAdmin.jsx
  src/containers/admin/DiagnosticAdmin.jsx
  src/containers/admin/MascotaAdmin.jsx
  src/containers/pages/MisMascotas.tsx
  src/containers/pages/PageAdoptPets.tsx
  src/functions/Admin/AdminAdoptPet.ts
  src/functions/Admin/AdminUsers.ts
  src/functions/adoptionFunction.ts
  src/interfaces/IPet.ts
  src/utils/LocalStorage.ts
Labels: feature

#11 add profile user
  src/App.tsx
  src/assets/css/style.css
  src/components/modals/ModalChangePassword.tsx
  src/components/navigation/Navbar.js
  src/components/userProfile/profile.tsx
  src/containers/admin/ClienteAdmin.jsx
  src/containers/pages/ProfileUser.tsx
  src/functions/AuthLogin.ts
  src/functions/profileFunction.ts
  src/interfaces/IUsers.ts
  src/utils/LocalStorage.ts
Labels: feature, refactor

#13 change-modals-and-code
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  src/App.tsx
  src/assets/css/style.css
  src/components/adminDiagnostic/adminDiagnostic.tsx
  src/components/adminPet/adminPet.tsx
  src/components/modals/ModalAdminPetAdopt.tsx
  src/components/modals/ModalAdminUsers.tsx
  src/components/navigation/Navbar.js
  src/components/pet/Mascota.tsx
  src/containers/admin/AdminAdoptionPage.tsx
  src/containers/pages/Diagnosticos.tsx
  src/containers/pages/Donate.tsx
  src/containers/pages/MisMascotas.tsx
  src/functions/Pets.ts
  src/utils/Auth.tsx
  src/utils/LocalStorage.ts
Labels: refactor
